### ISSUE TITLE
Server Side won't load

### ISSUE THREAD

**Issue by K4N0** [PersonTheCat/CatLib#2] opened 2022-10-24 04:03 UTC
Attempting to load this mod by itself and it won't startup.
An immediate error occurs. Fresh install and only 1 mod.

No crash, error:
https://pastebin.com/ytH8dzMc

Mods:
CatLib-Forge-2.5.jar

Forge:
forge-1.18.2-40.1.84

**Comment by PersonTheCat** [comment] 2023-04-06 18:23
Hello. Super sorry this has gone unfixed for _so_ long. Just had some other priorities to work on first, but I'm fixing it today. This will hopefully get OSV out of beta and make way for my next mod, Pangaea. Will update here when I get that figured out.

**Comment by PersonTheCat** [comment] 2023-04-10 21:01
Hey, this was fixed in 2.7. Will be out shortly and sorry for the wait. 

Slightly technical details: this was caused by an unmapped synthetic method not having a consistent intermediary name on the Forge platform between a couple minor updates. I did update the mapping, but long story short, this will continue to be a problem until I find a better fix. So far, my other fixes can all be easily broken by other mods. Will continue searching for a better fix and just get this out there in the meantime.

Please reopen this issue if you feel it has not been fixed. Thanks!

**Closed by PersonTheCat** 2023-04-10 21:01 UTC
